python compile.py --model gpt-3.5-turbo --file ../../input/selected_protocols/1.json
python compile.py --model gpt-3.5-turbo --file ../../input/selected_protocols/2.json
python compile.py --model gpt-3.5-turbo --file ../../input/selected_protocols/3.json
python compile.py --model gpt-3.5-turbo --file ../../input/selected_protocols/4.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-611.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-485.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-84.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-168.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-7285.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-4421.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-316.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-635.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-4319.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-163.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-110.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-136.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-3083.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-619.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-58.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-492.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2883.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-387.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2925.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-557.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2509.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-47.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-213.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2326.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-93.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-501.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-269.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-383.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-594.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2546.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-573.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-133.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2749.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-91.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-398.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-158.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2905.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-3155.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-374.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-3255.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-263.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2120.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-175.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-164.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-117.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-4411.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-460.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-48.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-320.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-400.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-282.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2893.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2715.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-132.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2909.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2396.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-102.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-380.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-3855.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-285.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-419.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-115.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-330.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-159.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2280.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2325.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-108.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-272.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-2566.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-4267.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-10.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-532.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-3783.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-51.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-5123.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-394.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-4933.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-416.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-258.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-78.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-3197.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-402.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-116.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-4399.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-3803.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-3659.json
python compile.py --model gpt-3.5-turbo --file ../../input/flatten_protocols/protocol_nprot-162.json